name: SpecialisedTools
version: 1.0
author: codedcosmos
main: codedcosmos.specialisedtools.core.ToolsPlugin
api-version: 1.16

commands:
  getspecialtool:
    description:
    usage: /getspecialtool [axe | pickaxe | hoe | shovel | sword]